version: '2'
services:
    mapa360aplicaciones-app:
        image: mapa360aplicaciones
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_CLOUD_CONSUL_HOST=consul
            - SPRING_CLOUD_CONSUL_PORT=8500
            - SPRING_DATASOURCE_URL=jdbc:mariadb://mapa360aplicaciones-mariadb:3306/mapa360aplicaciones
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://mapa360aplicaciones-elasticsearch:9200
    mapa360aplicaciones-mariadb:
        extends:
            file: mariadb.yml
            service: mapa360aplicaciones-mariadb
    mapa360aplicaciones-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: mapa360aplicaciones-elasticsearch
    consul:
        image: consul:1.2.3
        command: consul agent -dev -ui -client 0.0.0.0
        ports:
            - 8300:8300
            - 8500:8500
            - 8600:8600

    consul-config-loader:
        image: jhipster/consul-config-loader:v0.3.0
        volumes:
            - ./central-server-config:/config
        environment:
            - INIT_SLEEP_SECONDS=5
            - CONSUL_URL=consul
            - CONSUL_PORT=8500
        # Uncomment to load configuration into Consul from a Git repository
        # as configured in central-server-config/git2consul.json
        # Also set SPRING_CLOUD_CONSUL_CONFIG_FORMAT=files on your apps
        #    - CONFIG_MODE=git
